name: First Workflow
on:
  push:
    branches:
      - main   

jobs:
   firstjob:
     runs-on:  ubuntu-latest        
     steps:   
        - name: firststep
          run: echo "first step runnen"           
        - name: second step
          run: echo "second steb running"           
        - name: third step checkout repository
          uses:  actions/checkout@v6.0.1
        - name: list all files 
          run: |
           echo "all files in directory"
           ls la
