on:
  workflow_dispatch
jobs:
  Testing-Application:    
    runs-on: ubuntu-latest
    steps:
      - name: Testing-steps
        run: echo "testing is running.."
  Hosting-application:
    runs-on: ubuntu-latest
    steps:
      - name: hosting-steps
        run: echo "hosting is running..."
      
